---
driver:
  name: vagrant
  linked_clone: true
  require_chef_omnibus: 13

provisioner:
  name: chef_zero
  log_level: debug

verifier:
  name: inspec
  inspec_tests:
    - test/inspec

platforms:
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[knotx::_install]
    attributes:
      knotx:
        debug_enabled: true
