---
<% chef_versions = %w( 13 14 ) %>
<% platforms = %w( centos-6 centos-7 ) %>

driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero
  log_level: <%= ENV['TK_CHEF_LOG_LEVEL'] || 'info' %>

verifier:
  name: inspec
  inspec_tests:
    - test/inspec

platforms:
<% platforms.each do |p| %>
<%   chef_versions.each do |chef_version| %>
  - name: <%= p %>-chef-<%= chef_version %>
    driver_config:
      box: bento/<%= p %>
      require_chef_omnibus: <%= chef_version %>
    attributes:
      knotx:
        # TODO: replace with proper URL after knot.x 1.3.0 release
        url: 'https://oss.sonatype.org/content/repositories/snapshots/io/knotx/knotx-stack-manager/1.3.0-SNAPSHOT/knotx-stack-manager-1.3.0-20180425.065432-12.zip'
      java:
        jdk:
          '8':
            x86_64:
              url: <%= ENV['JAVA_JDK_8_X86_64_URL'] || 'http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz' %>
              checksum: <%= ENV['JAVA_JDK_8_X86_64_CHECKSUM'] || '28a00b9400b6913563553e09e8024c286b506d8523334c93ddec6c9ec7e9d346' %>
<%   end %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[knotx::_install]
