---
driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[knotx_test::install_main]
      - recipe[knotx_test::install_main2]
    attributes:
  - name: git_config
    run_list:
      - recipe[knotx_test::install_main]
      - recipe[knotx_test::install_main2]
    attributes:
      knotx:
        config:
          git_enabled: true
          git_dir: '/opt/knotx/config'
        app_config_path: '/opt/knotx/config/knotx-standalone/src/main/resources/knotx-standalone.json'

