---
<% chef_versions = %w( 13 14 ) %>
<% platforms = %w( centos-6 centos-7 ) %>

driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero
  log_level: <%= ENV['TK_CHEF_LOG_LEVEL'] || 'info' %>

verifier:
  name: inspec
  inspec_tests:
    - test/inspec

platforms:
<% platforms.each do |p| %>
<%   chef_versions.each do |chef_version| %>
  - name: <%= p %>-chef-<%= chef_version %>
    driver_config:
      box: bento/<%= p %>
      require_chef_omnibus: <%= chef_version %>
    attributes:
      knotx:
        url: 'https://oss.sonatype.org/content/groups/public/io/knotx/knotx-stack-manager/1.3.0-SNAPSHOT/knotx-stack-manager-1.3.0-20180417.122358-11.zip'
      java:
        jdk:
          '8':
            x86_64:
              url: <%= ENV['JAVA_JDK_8_X86_64_URL'] || 'http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jdk-8u162-linux-x64.tar.gz' %>
              checksum: <%= ENV['JAVA_JDK_8_X86_64_CHECKSUM'] || '68ec82d47fd9c2b8eb84225b6db398a72008285fafc98631b1ff8d2229680257' %>
<%   end %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[knotx::_install]
