---
<% chef_versions = %w( 13 14 ) %>
<% platforms = %w( centos-6 centos-7 ) %>

driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero
  log_level: <%= ENV['TK_CHEF_LOG_LEVEL'] || 'info' %>

verifier:
  name: inspec
  inspec_tests:
    - test/inspec

platforms:
<% platforms.each do |p| %>
<%   chef_versions.each do |chef_version| %>
  - name: <%= p %>-chef-<%= chef_version %>
    driver_config:
      box: bento/<%= p %>
      require_chef_omnibus: <%= chef_version %>
<%   end %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[knotx::_install]
    attributes:
      knotx:
        debug_enabled: true
