---
driver:
  name: vagrant
  linked_clone: true

provisioner:
  name: chef_zero

verifier:
  name: inspec
  inspec_tests:
    - test/inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3

suites:
  - name: config_file
    run_list:
      - recipe[knotx::_install]
    attributes:
  - name: config_git
    run_list:
      - recipe[knotx::_install]
    attributes:
      knotx:
        config:
          git_enabled: true
          git_dir: '/opt/knotx/config'
        app_config_path: '/opt/knotx/config/knotx-standalone/src/main/resources/knotx-standalone.json'

